# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CpaPlusplus < Formula
  desc "OpenAI/Gemini/Claude/Codex compatible API proxy with OAuth and round-robin load balancing"
  homepage "https://github.com/nguyenphutrong/cpa-plusplus"
  version "7.1.38-plus.3"
  license "MIT"

  depends_on "git" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nguyenphutrong/cpa-plusplus/releases/download/v7.1.38-plus.3/cpa-plusplus_7.1.38-plus.3_darwin_amd64.tar.gz"
      sha256 "94001caa2875333f5b2283cefc675acec16421d3d0005d3e614d9a06d71ab11f"

      define_method(:install) do
        bin.install "cpa-plusplus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nguyenphutrong/cpa-plusplus/releases/download/v7.1.38-plus.3/cpa-plusplus_7.1.38-plus.3_darwin_aarch64.tar.gz"
      sha256 "70b536e6744c853f6de484ae527d239455ddb7926b876b5dbd81c119356ccc5b"

      define_method(:install) do
        bin.install "cpa-plusplus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenphutrong/cpa-plusplus/releases/download/v7.1.38-plus.3/cpa-plusplus_7.1.38-plus.3_linux_amd64.tar.gz"
      sha256 "1845f82ae3eb650aa8a2ac4227541748d0ac700c47430b8ba97ea9de5f8eb436"
      define_method(:install) do
        bin.install "cpa-plusplus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenphutrong/cpa-plusplus/releases/download/v7.1.38-plus.3/cpa-plusplus_7.1.38-plus.3_linux_aarch64.tar.gz"
      sha256 "7089b5d9599f01e462f51deaf218f36a98a45771d5c6d72cebed20ad23edc0ca"
      define_method(:install) do
        bin.install "cpa-plusplus"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/cpa-plusplus --version")
  end
end
